github_actions:
  stage:
    - dry-run
    - cq-test
  runner:
    type: github-actions
    workflow: commit-queue.yml

github_actions2:
  stage:
    - cq-test
  runner:
    type: github-actions
    workflow: commit-queue.yml
