# This is a basic workflow to help you get started with Actions

name: CQ

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for all the branches
  push:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to preprare necessary check runs for commit queue
  Prepare:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: CommitQueue
          status: in_progress
          output: |
            {"summary": "The purpose of this job is solely to indicate the status of the Commit Queue, so it may not be meaningful to developers who are not directly involved. If this job fails, please review the results of other jobs for more information."}
