name: Test Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  build1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  build2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  test:
    needs:
    - build1
    - build2
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  deploy:
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
