name: Test Actions
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 

  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  build1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  build2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
  test:
    needs:
    - build1
    - build2
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
  deploy:
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"
