name: Commit Queue Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      revision:
        description: "The revision of the source code to checkout"
        required: true
        type: string
      fetch_depth:
        description: "The depth to fetch"
        default: '1'
        type: number
      id:
        description: "The unique identifier to indentify the workflow run"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jianliang00/commit-queue-actions@0ce6211a356d07bd21020376130dcf3bcc300046
      
      # Add your steps here
      - name: Build
        run: echo "Your commands here"
