name: Commit Queue Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jianliang00/commit-queue-actions@0ce6211a356d07bd21020376130dcf3bcc300046
      
      # Add your steps here
      - name: Build
        run: echo "Your commands here"
